### ISSUE TITLE
O-X2 | Unable to deal with internal edits of user inputs.

### ISSUE THREAD

**Issue by Kenny-Krypto** [Kenny-Krypto/K-DXcipher#2]
No code included to deal with internal edits yet.
-if one edits the middle of text it removes from the end and doesn't update remaining translated text.
-if one changes 1 char (highlight and change char) doesn't update translated text.

**Comment by Kenny-Krypto** [comment]
Highlight Issues Fixed: b822ab3

**Comment by Kenny-Krypto** [comment]
Internal edit of source Text is now properly reflecting in translated text fixed: 6f601a3a71fcc0b9b22e46eb878ec6bf9e171db4

**Comment by JephteyAdolphe** [comment]
good job debugging this issue Mr. Bui!
